#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
xrandr --dpi 90 # Set DPI. User may want to use a larger number for larger screens.
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
feh --bg-fill ~/Pictures/wallpapers/Isaak_Levitan_Tihaya_obitel.jpg

dbus-update-activation-environment --all
gnome-keyring-daemon --start --components=secrets
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#polkit-dumb-agent
export QT_QPA_PLATFORM=xcb
autostart="dunst opensnitch-ui  picom"

for program in $autostart; do
  pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
